name: Go Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Run Go Linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest && golangci-lint run
  build:
    runs-on: ubuntu-latest
    needs: lint  # Зависимость от job 'lint'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build MySQL Test Image
        run: |
          docker build -t mysql_test -f testdb.Dockerfile .

  test:
    runs-on: ubuntu-latest
    needs: [lint, build]  # Зависимость от job 'lint' и 'build'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Run MySQL Test Container
        run: |
          docker run --name mysql-test-container -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=student_project_management_test -e MYSQL_USER=owner -e MYSQL_PASSWORD=root -p 3308:3306 -d mysql_test

      - name: Run Go Tests
        run: go test ./... -v